first_name = input('Hi! Please enter your first name: ')
last_name = input('Hi! Please enter your last name: ')
print(f'Hello, {first_name} {last_name}!')
house_number = input('Please enter your house number: ')
street = input('Please enter your street name: ')
postcode = input('Please enter your postcode: ')
print('Your address is ' + str(house_number) + ' ' + street + ', ' + postcode)
