print('Hi! Please enter your first name:')
first_name = input()
print('Hi! Please enter your last name:')
last_name = input()
print(f'Hello, {first_name} {last_name}!')
print('Please enter your house number:')
house_number = input()
print('Please enter your street name:')
street = input()
print('Please enter your postcode:')
postcode = input()
print("Your address is " + str(house_number) + " " + street + ", " + postcode)
